CREATE TABLE Country(idCountry INT, code VARCHAR(2), name VARCHAR(25), PRIMARY KEY (idCountry));
INSERT OR REPLACE INTO Country VALUES (1, "GB", "United Kingdom");
INSERT OR REPLACE INTO Country VALUES (2, "US", "United States");
INSERT OR REPLACE INTO Country VALUES (3, "CA", "Canada");
INSERT OR REPLACE INTO Country VALUES (4, "AU", "Australia");
INSERT OR REPLACE INTO Country VALUES (5, "NO", "Norway");
INSERT OR REPLACE INTO Country VALUES (6, "IT", "Italy");
INSERT OR REPLACE INTO Country VALUES (7, "DE", "Germany");
INSERT OR REPLACE INTO Country VALUES (8, "IE", "Ireland");
INSERT OR REPLACE INTO Country VALUES (9, "MX", "Mexico");
INSERT OR REPLACE INTO Country VALUES (10, "ES", "Spain");
INSERT OR REPLACE INTO Country VALUES (11, "SE", "Sweden");
INSERT OR REPLACE INTO Country VALUES (12, "FR", "France");
INSERT OR REPLACE INTO Country VALUES (13, "NL", "Netherlands");
INSERT OR REPLACE INTO Country VALUES (14, "NZ", "New Zealand");
INSERT OR REPLACE INTO Country VALUES (15, "CH", "Switzerland");
INSERT OR REPLACE INTO Country VALUES (16, "AT", "Austria");
INSERT OR REPLACE INTO Country VALUES (17, "DK", "Denmark");
INSERT OR REPLACE INTO Country VALUES (18, "BE", "Belgium");
INSERT OR REPLACE INTO Country VALUES (19, "HK", "Hong Kong");
INSERT OR REPLACE INTO Country VALUES (20, "LU", "Luxembourg");
INSERT OR REPLACE INTO Country VALUES (21, "SG", "Singapore");
INSERT OR REPLACE INTO Country VALUES (22, "JP", "Japan");
