CREATE TABLE MainCategory(idMainCategory INT, name VARCHAR(50), PRIMARY KEY (idMainCategory));
INSERT OR REPLACE INTO MainCategory VALUES (1, "Publishing");
INSERT OR REPLACE INTO MainCategory VALUES (2, "Film & Video");
INSERT OR REPLACE INTO MainCategory VALUES (3, "Music");
INSERT OR REPLACE INTO MainCategory VALUES (4, "Food");
INSERT OR REPLACE INTO MainCategory VALUES (5, "Design");
INSERT OR REPLACE INTO MainCategory VALUES (6, "Crafts");
INSERT OR REPLACE INTO MainCategory VALUES (7, "Games");
INSERT OR REPLACE INTO MainCategory VALUES (8, "Comics");
INSERT OR REPLACE INTO MainCategory VALUES (9, "Fashion");
INSERT OR REPLACE INTO MainCategory VALUES (10, "Theater");
INSERT OR REPLACE INTO MainCategory VALUES (11, "Art");
INSERT OR REPLACE INTO MainCategory VALUES (12, "Photography");
INSERT OR REPLACE INTO MainCategory VALUES (13, "Technology");
INSERT OR REPLACE INTO MainCategory VALUES (14, "Dance");
INSERT OR REPLACE INTO MainCategory VALUES (15, "Journalism");
