CREATE TABLE Category(idCategory INT, nameCategory VARCHAR(50), PRIMARY KEY (idCategory));
REPLACE INTO Category VALUES (1, "Music");
REPLACE INTO Category VALUES (2, "Games");
REPLACE INTO Category VALUES (3, "3D Printing");
REPLACE INTO Category VALUES (4, "Indie Rock");
REPLACE INTO Category VALUES (5, "Science Fiction");
REPLACE INTO Category VALUES (6, "Product Design");
REPLACE INTO Category VALUES (7, "Gadgets");
REPLACE INTO Category VALUES (8, "Country & Folk");
REPLACE INTO Category VALUES (9, "Nonfiction");
REPLACE INTO Category VALUES (10, "Rock");
REPLACE INTO Category VALUES (11, "Webseries");
REPLACE INTO Category VALUES (12, "Metal");
REPLACE INTO Category VALUES (13, "Art Books");
REPLACE INTO Category VALUES (14, "Animation");
REPLACE INTO Category VALUES (15, "Children's Books");
REPLACE INTO Category VALUES (16, "Video Games");
REPLACE INTO Category VALUES (17, "Photography");
REPLACE INTO Category VALUES (18, "Art");
REPLACE INTO Category VALUES (19, "Small Batch");
REPLACE INTO Category VALUES (20, "Tabletop Games");
REPLACE INTO Category VALUES (21, "Comic Books");
REPLACE INTO Category VALUES (22, "Food");
REPLACE INTO Category VALUES (23, "Apparel");
REPLACE INTO Category VALUES (24, "Shorts");
REPLACE INTO Category VALUES (25, "Fashion");
REPLACE INTO Category VALUES (26, "Hardware");
REPLACE INTO Category VALUES (27, "Film & Video");
REPLACE INTO Category VALUES (28, "Sound");
REPLACE INTO Category VALUES (29, "Public Art");
REPLACE INTO Category VALUES (30, "Design");
REPLACE INTO Category VALUES (31, "Publishing");
REPLACE INTO Category VALUES (32, "Comedy");
REPLACE INTO Category VALUES (33, "Couture");
REPLACE INTO Category VALUES (34, "Crafts");
REPLACE INTO Category VALUES (35, "Action");
REPLACE INTO Category VALUES (36, "Knitting");
REPLACE INTO Category VALUES (37, "Faith");
REPLACE INTO Category VALUES (38, "Food Trucks");
REPLACE INTO Category VALUES (39, "People");
REPLACE INTO Category VALUES (40, "Accessories");
REPLACE INTO Category VALUES (41, "Documentary");
REPLACE INTO Category VALUES (42, "Pop");
REPLACE INTO Category VALUES (43, "DIY");
REPLACE INTO Category VALUES (44, "Playing Cards");
REPLACE INTO Category VALUES (45, "Poetry");
REPLACE INTO Category VALUES (46, "Theater");
REPLACE INTO Category VALUES (47, "Sculpture");
REPLACE INTO Category VALUES (48, "Farms");
REPLACE INTO Category VALUES (49, "Fiction");
REPLACE INTO Category VALUES (50, "Narrative Film");
REPLACE INTO Category VALUES (51, "Interactive Design");
REPLACE INTO Category VALUES (52, "Television");
REPLACE INTO Category VALUES (53, "Conceptual Art");
REPLACE INTO Category VALUES (54, "Technology");
REPLACE INTO Category VALUES (55, "Anthologies");
REPLACE INTO Category VALUES (56, "Comics");
REPLACE INTO Category VALUES (57, "Painting");
REPLACE INTO Category VALUES (58, "Experimental");
REPLACE INTO Category VALUES (59, "Plays");
REPLACE INTO Category VALUES (60, "Nature");
REPLACE INTO Category VALUES (61, "Jazz");
REPLACE INTO Category VALUES (62, "Installations");
REPLACE INTO Category VALUES (63, "Performance Art");
REPLACE INTO Category VALUES (64, "Family");
REPLACE INTO Category VALUES (65, "Radio & Podcasts");
REPLACE INTO Category VALUES (66, "Apps");
REPLACE INTO Category VALUES (67, "Places");
REPLACE INTO Category VALUES (68, "Electronic Music");
REPLACE INTO Category VALUES (69, "Illustration");
REPLACE INTO Category VALUES (70, "Literary Journals");
REPLACE INTO Category VALUES (71, "Performances");
REPLACE INTO Category VALUES (72, "Drinks");
REPLACE INTO Category VALUES (73, "Thrillers");
REPLACE INTO Category VALUES (74, "Dance");
REPLACE INTO Category VALUES (75, "Software");
REPLACE INTO Category VALUES (76, "R&B");
REPLACE INTO Category VALUES (77, "Web");
REPLACE INTO Category VALUES (78, "Horror");
REPLACE INTO Category VALUES (79, "Graphic Novels");
REPLACE INTO Category VALUES (80, "Footwear");
REPLACE INTO Category VALUES (81, "Graphic Design");
REPLACE INTO Category VALUES (82, "Hip-Hop");
REPLACE INTO Category VALUES (83, "Latin");
REPLACE INTO Category VALUES (84, "Immersive");
REPLACE INTO Category VALUES (85, "Fabrication Tools");
REPLACE INTO Category VALUES (86, "Architecture");
REPLACE INTO Category VALUES (87, "Live Games");
REPLACE INTO Category VALUES (88, "Periodicals");
REPLACE INTO Category VALUES (89, "Mixed Media");
REPLACE INTO Category VALUES (90, "Digital Art");
REPLACE INTO Category VALUES (91, "World Music");
REPLACE INTO Category VALUES (92, "Drama");
REPLACE INTO Category VALUES (93, "Woodworking");
REPLACE INTO Category VALUES (94, "Wearables");
REPLACE INTO Category VALUES (95, "Video");
REPLACE INTO Category VALUES (96, "Calendars");
REPLACE INTO Category VALUES (97, "Photobooks");
REPLACE INTO Category VALUES (98, "Gaming Hardware");
REPLACE INTO Category VALUES (99, "Musical");
REPLACE INTO Category VALUES (100, "Robots");
REPLACE INTO Category VALUES (101, "Festivals");
REPLACE INTO Category VALUES (102, "Quilts");
REPLACE INTO Category VALUES (103, "Classical Music");
REPLACE INTO Category VALUES (104, "Space Exploration");
REPLACE INTO Category VALUES (105, "Ceramics");
REPLACE INTO Category VALUES (106, "Photo");
REPLACE INTO Category VALUES (107, "Events");
REPLACE INTO Category VALUES (108, "Academic");
REPLACE INTO Category VALUES (109, "Fine Art");
REPLACE INTO Category VALUES (110, "Young Adult");
REPLACE INTO Category VALUES (111, "Restaurants");
REPLACE INTO Category VALUES (112, "Mobile Games");
REPLACE INTO Category VALUES (113, "Community Gardens");
REPLACE INTO Category VALUES (114, "Spaces");
REPLACE INTO Category VALUES (115, "Journalism");
REPLACE INTO Category VALUES (116, "Makerspaces");
REPLACE INTO Category VALUES (117, "DIY Electronics");
REPLACE INTO Category VALUES (118, "Childrenswear");
REPLACE INTO Category VALUES (119, "Jewelry");
REPLACE INTO Category VALUES (120, "Farmer's Markets");
REPLACE INTO Category VALUES (121, "Webcomics");
REPLACE INTO Category VALUES (122, "Print");
REPLACE INTO Category VALUES (123, "Camera Equipment");
REPLACE INTO Category VALUES (124, "Glass");
REPLACE INTO Category VALUES (125, "Kids");
REPLACE INTO Category VALUES (126, "Stationery");
REPLACE INTO Category VALUES (127, "Ready-to-wear");
REPLACE INTO Category VALUES (128, "Literary Spaces");
REPLACE INTO Category VALUES (129, "Zines");
REPLACE INTO Category VALUES (130, "Animals");
REPLACE INTO Category VALUES (131, "Movie Theaters");
REPLACE INTO Category VALUES (132, "Blues");
REPLACE INTO Category VALUES (133, "Printing");
REPLACE INTO Category VALUES (134, "Punk");
REPLACE INTO Category VALUES (135, "Civic Design");
REPLACE INTO Category VALUES (136, "Textiles");
REPLACE INTO Category VALUES (137, "Bacon");
REPLACE INTO Category VALUES (138, "Embroidery");
REPLACE INTO Category VALUES (139, "Fantasy");
REPLACE INTO Category VALUES (140, "Music Videos");
REPLACE INTO Category VALUES (141, "Cookbooks");
REPLACE INTO Category VALUES (142, "Vegan");
REPLACE INTO Category VALUES (143, "Weaving");
REPLACE INTO Category VALUES (144, "Puzzles");
REPLACE INTO Category VALUES (145, "Pet Fashion");
REPLACE INTO Category VALUES (146, "Video Art");
REPLACE INTO Category VALUES (147, "Translations");
REPLACE INTO Category VALUES (148, "Crochet");
REPLACE INTO Category VALUES (149, "Candles");
REPLACE INTO Category VALUES (150, "Typography");
REPLACE INTO Category VALUES (151, "Romance");
REPLACE INTO Category VALUES (152, "Flight");
