CREATE TABLE Currency(idCurrency INTEGER, code VARCHAR(3), nameCurrency VARCHAR(25), changeRate FLOAT, PRIMARY KEY (idCurrency));
REPLACE INTO Currency VALUES (1, "USD", "US Dollar", 1.0);
REPLACE INTO Currency VALUES (2, "GBP", "Great British Pound", 1.23);
REPLACE INTO Currency VALUES (3, "EUR", "Euro", 1.11);
REPLACE INTO Currency VALUES (4, "CAD", "Canadian Dollar", 0.72);
REPLACE INTO Currency VALUES (5, "SEK", "Swedish Krona", 0.1);
REPLACE INTO Currency VALUES (6, "NZD", "New Zealand Dollar", 0.61);
REPLACE INTO Currency VALUES (7, "AUD", "Australian Dollar", 0.61);
REPLACE INTO Currency VALUES (8, "HKD", "Hong Kong Dollar", 0.13);
REPLACE INTO Currency VALUES (9, "MXN", "Mexican Peso", 0.04);
REPLACE INTO Currency VALUES (10, "NOK", "Norwegian Krone", 0.1);
REPLACE INTO Currency VALUES (11, "DKK", "Danish Krone", 0.15);
REPLACE INTO Currency VALUES (12, "SGD", "Singapore Dollar", 0.7);
REPLACE INTO Currency VALUES (13, "CHF", "Swiss Franc", 1.06);
